name: Test CI
on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches-ignore:
      - "master"
jobs:
  test:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Run tests
        run: deno test --allow-read
  bench:
    name: benchmark
    runs-on: ubuntu
    needs: test
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Run benchmarks
        run: deno bench --unstable .
